### ISSUE TITLE
new website

### ISSUE THREAD

**Issue by lkc3093** [ZyqGitHub1/h-player-v2#13]
如何导入自定义网站呢

**Comment by ZyqGitHub1** [comment]
Sorry, the current version only supports importing video source sites provided by the project. Download and import video sources, please see the following gif
[download](https://raw.githubusercontent.com/ZyqGitHub1/h-player-v2/master/screenshot/download-sorce.gif)
[import](https://raw.githubusercontent.com/ZyqGitHub1/h-player-v2/master/screenshot/import-source.gif)

----------

抱歉，目前版本只支持导入项目提供的视频源网站。下载和导入视频源请看以下gif
[下载](https://raw.githubusercontent.com/ZyqGitHub1/h-player-v2/master/screenshot/download-sorce.gif)
[导入](https://raw.githubusercontent.com/ZyqGitHub1/h-player-v2/master/screenshot/import-source.gif)
