### ISSUE TITLE
配置文件的页面打不开，可以放个下载链接吗？

### ISSUE THREAD

**Issue by f4851947** [ZyqGitHub1/h-player-v2#14]
配置文件的页面打不开，可以放个下载链接吗？

**Comment by f4851947** [comment]
视频源文件链接打不开，无法保存。

**Comment by tujidelv** [comment]
windows下 打开C:\Windows\System32\drivers\etc\hosts文件
编辑器打开，在最后行添加192.30.253.118 gist.github.com
保存即可。

**Comment by ZyqGitHub1** [comment]
链接：https://pan.baidu.com/s/1nOlT4bH_VtUqQm4WmrN3qg 
提取码：ltch
