### ISSUE TITLE
大佬，视频网站的json怎么做的

### ISSUE THREAD

**Issue by dpk3** [ZyqGitHub1/h-player-v2#19]
本人纯小白，我想试试一些常规的影视资源http://www.jisudhw.com/，却不会弄url httpapi什么的那些网址是怎么获取的，求大神赐教

**Comment by ZyqGitHub1** [comment]
Website apis using php cms are similar, so you only need to modify some details when parsing the returned xml. At present, these xml parsing functions are built-in and cannot adapt to the differences of details of different websites. I think there are several ways to solve this problem.
1. Improve the compatibility of built-in analytic functions
2. Provide a way to customize the analytic function

I will explain these issues in detail when I start to improve the development documentation.


-------

使用php cms的网站api都是类似的，所以仅仅在解析返回的xml的时候需要修改一些细节。目前这些xml解析函数都是内置的，不能适配不同网站的细节差异，我想有以下几个方式来解决这个问题
1. 提升内置解析函数的兼容性
2. 提供自定义解析函数的方式

我会在着手完善开发文档的时候详细解释这些问题

**Comment by woaijorden** [comment]
大佬加油！

**Comment by anglesgirl** [comment]
**http://www.jisudhw.com/help/#MacCms10**
别人网站里已经提供帮助了 你把东西提取出来 自己编辑一下就可以了

**Comment by ZyqGitHub1** [comment]
#23
