### ISSUE TITLE
老铁，支持你。

### ISSUE THREAD

**Issue by 1483746124** [ZyqGitHub1/h-player-v2#20]
不过怎么样才能，上传到自己网站和别人一起看？ 
看了一下别的问题，现在还不能呢 对吧 
只能自己看？

**Comment by ZyqGitHub1** [comment]
For your question, my understanding is that you want to build a website for video online. However, this project is a video player and cannot provide online playback services. The video source of the player is the resource collection network. Most resource collection networks offer api and online playback services. So you can use the CMS supported by the Resource Collection Network to build your own online playback service.
Here are a few websites for reference:
+ https://www.51ckx.com/index_caiji.html
+ http://www.jisudhw.com/help/#SeaCms

------

对于你提出的问题，我的理解是你想搭建一个视频在线播放的网站。但是本项目是一个视频播放器，不能提供在线播放服务。播放器的视频来源是资源采集网。大多数资源采集网都提供api和在线播放服务。所以你可以使用资源采集网支持的CMS搭建自己的在线播放服务。
这是几个可供参考的网站：
+ https://www.51ckx.com/index_caiji.html
+ http://www.jisudhw.com/help/#SeaCms

**Comment by 1483746124** [comment]
感谢告知，其中的这些网站我也去过但不同的是你给我的这网站模板可以下载。
------------------------------------------------------------------------------------------------------
这渔 ，我所欲也，有时间来监狱看我


------------------ 原始邮件 ------------------
发件人: "ZyqGitHub1"<notifications@github.com>;
发送时间: 2019年8月2日(星期五) 下午5:30
收件人: "ZyqGitHub1/h-player-v2"<h-player-v2@noreply.github.com>;
抄送: "Indulge"<1483746124@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [ZyqGitHub1/h-player-v2] 老铁，支持你。 (#20)




For your question, my understanding is that you want to build a website for video online. However, this project is a video player and cannot provide online playback services. The video source of the player is the resource collection network. Most resource collection networks offer api and online playback services. So you can use the CMS supported by the Resource Collection Network to build your own online playback service.
 Here are a few websites for reference:
  
https://www.51ckx.com/index_caiji.html
 
http://www.jisudhw.com/help/#SeaCms
  
 
对于你提出的问题，我的理解是你想搭建一个视频在线播放的网站。但是本项目是一个视频播放器，不能提供在线播放服务。播放器的视频来源是资源采集网。大多数资源采集网都提供api和在线播放服务。所以你可以使用资源采集网支持的CMS搭建自己的在线播放服务。
 这是几个可供参考的网站：
  
https://www.51ckx.com/index_caiji.html
 
http://www.jisudhw.com/help/#SeaCms

**Comment by 1483746124** [comment]
大佬，我还有一个疑问想问，就是说想做一个像猫咪APP那样的客户端（它使用的类似于快手的手机端模板），现在我还毫无头绪。求解




------------------ 原始邮件 ------------------
发件人: "ZyqGitHub1"<notifications@github.com>;
发送时间: 2019年8月2日(星期五) 下午5:30
收件人: "ZyqGitHub1/h-player-v2"<h-player-v2@noreply.github.com>;
抄送: "Indulge"<1483746124@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [ZyqGitHub1/h-player-v2] 老铁，支持你。 (#20)




For your question, my understanding is that you want to build a website for video online. However, this project is a video player and cannot provide online playback services. The video source of the player is the resource collection network. Most resource collection networks offer api and online playback services. So you can use the CMS supported by the Resource Collection Network to build your own online playback service.
 Here are a few websites for reference:
  
https://www.51ckx.com/index_caiji.html
 
http://www.jisudhw.com/help/#SeaCms
  
 
对于你提出的问题，我的理解是你想搭建一个视频在线播放的网站。但是本项目是一个视频播放器，不能提供在线播放服务。播放器的视频来源是资源采集网。大多数资源采集网都提供api和在线播放服务。所以你可以使用资源采集网支持的CMS搭建自己的在线播放服务。
 这是几个可供参考的网站：
  
https://www.51ckx.com/index_caiji.html
 
http://www.jisudhw.com/help/#SeaCms
