### ISSUE TITLE
添加清晰度的选择

### ISSUE THREAD

**Issue by yoyoyoohh** [ZyqGitHub1/h-player-v2#24]
如题，能否添加选择清晰度的功能

**Comment by ZyqGitHub1** [comment]
Video resolutionis determined by the video source. The video source is provided by some third-party resource collection networks. If the video source only provides a video resolutionis, then no other resolution can be selected in the software.

-------

视频清晰度由视频源决定。视频源由一些第三方资源采集网提供。如果视频源仅仅提供了一种视频清晰度，那么在软件中也无法选择其他清晰度。
