### ISSUE TITLE
为了方便下载，建议如下

### ISSUE THREAD

**Issue by anglesgirl** [ZyqGitHub1/h-player-v2#26]
https://cdn.jsdelivr.net/gh/ZyqGitHub1/h-player-v2@latest/src/

这是jd提供的加速cdn，可以直接读取github的文件
你的成品或者源码使用目录分别存好
就可以直接用
https://cdn.jsdelivr.net/gh/用户名/项目名/文件夹 的方式访问
国内可以高速访问，直接项目的跟目录无法列出出目录，但是可以文件直连
当然这不是多大的问题，只是方便某些网络不好的人可以直接获取文件
你也知道国内特别是移动网根本下载不了github的文件

说明下，这个加速国内是网宿提供，国外是cloudflare提供，不需要做任何注册，你只需要把github目录调整一下即可

**Comment by ZyqGitHub1** [comment]
The code repository is primarily for version control and open source sharing. The binary release version, if placed in the code repository, makes the repository too bloated, and git can't effectively track binary changes. So I won't put the binary distribution in the code repository.

------

代码仓库主要是为了版本控制和开源共享。而二进制发布版本如果放在代码仓库中会使得仓库过于臃肿 ，并且git无法有效跟踪二进制文件的变动。所以我不会将二进制发布版本放在代码仓库中。
