### ISSUE TITLE
如何才能在服务器nodejs中直接运行呢，而不是在electron中

### ISSUE THREAD

**Issue by 119977** [ZyqGitHub1/h-player-v2#27]
如何才能在服务器nodejs中直接运行呢，而不是在electron中

**Comment by ZyqGitHub1** [comment]
This project is based on the Quasar Framework development. The software uses the vuejs development interface. Most of the feature implementations are also in the vue component. If you want to get rid of the electron environment, you may need to separate some of the function code from the vue component. You can read the code and try to refactor using nodejs.

------

这个项目是基于Quasar Framework开发。软件使用vuejs开发界面。大多数的功能实现也是在vue组件之中。如果想脱离electron环境，可能需要将部分功能代码从vue组件之中分离。你可以阅读代码并尝试使用nodejs重构。
