### ISSUE TITLE
链接打不开

### ISSUE THREAD

**Issue by kingdee88** [ZyqGitHub1/h-player-v2#30]
![image](https://user-images.githubusercontent.com/12748385/62433123-b6534080-b765-11e9-9889-2d74212aa117.png)

**Comment by ZyqGitHub1** [comment]
Some video sources cannot obtain data because the api of the corresponding resource collection network is abnormal and cannot be accessed. Need to wait for the resource collection network to fix the api.

------

部分视频源无法获取数据是因为对应的资源采集网的api出现异常无法访问。需要等待资源采集网修复api。
