### ISSUE TITLE
搜索功能还是不正常

### ISSUE THREAD

**Issue by anglesgirl** [ZyqGitHub1/h-player-v2#38]
搜索功能不能使用 所有的
不知道是不是旧版本遗留问题

如果搜索上有文字 切换片源后 直接是不能进行搜索 需要修改框内文字后才能启动搜索 直接回车无反应 

进行搜索页面有反应 但是不会出现任何搜索结果出现 页面就闪一下回到原来样子

新版本的API还是完全不支持
https://www.miaobozy.com/ 这家用的就是新的API

**Comment by anglesgirl** [comment]
顺便看了几个资源站 能拉取到片子的图片名字和集数  播放连接却是空的
不能正常播放

**Comment by ZyqGitHub1** [comment]
Please download the release version above 0.8.0 and try

------

请下载0.8.0以上的release版本尝试
