### ISSUE TITLE
电视剧选集功能

### ISSUE THREAD

**Issue by GeorgeJu95** [ZyqGitHub1/h-player-v2#42]
你好，**电视剧资源**打开后都是只有第一集，请问能加一个可以**选集**的功能吗？

**Comment by ZyqGitHub1** [comment]
Please indicate the version and website where the issue occurred

------

请说明出现问题的版本和网站

**Comment by GeorgeJu95** [comment]
release中的0.8.0版本, 所有的网站都不能加载选集，ok资源，麻花资源，酷云资源等等。

**Comment by ZyqGitHub1** [comment]
> 
> 
> release中的0.8.0版本, 所有的网站都不能加载选集，ok资源，麻花资源，酷云资源等等。

我本地测试无法复现问题，请确保添加符合maccms8规范的m3u8资源的api，下面是我ok资源网的配置示例

```json
{
    "id": "2e4fc1b5-583e-4620-b3e0-5c2fb90cad5c",
    "name": "ok资源网站",
    "uri": "http://www.jisudhw.com",
    "httpApi": "http://cj.okzy.tv/inc/apickm3u8.php",
    "httpsApi": "http://cj.okzy.tv/inc/apickm3u8s.php",
    "type": "影视",
  }
```

**Comment by GeorgeJu95** [comment]
刚刚解决了，谢谢！
