### ISSUE TITLE
可否提供百度云链接，github下载实在慢，还老不成功

### ISSUE THREAD

**Issue by joylin1984** [ZyqGitHub1/h-player-v2#49]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ZyqGitHub1** [comment]
Version 0.9.3 has provided the download link of Baidu Disk.

------

0.9.3版本已提供对应的百度网盘下载链接
