### ISSUE TITLE
无法导入视频源

### ISSUE THREAD

**Issue by rog-mail** [ZyqGitHub1/h-player-v2#56]

**Comment by rog-mail** [comment]
选择视频源json文件后软件无反应

**Comment by rog-mail** [comment]
请问作者视频源列表能否加入排序功能啊能手动调整顺序

**Comment by xiuzigege** [comment]
> 选择视频源json文件后软件无反应

老哥  你怎么解决的

**Comment by rog-mail** [comment]
> > 选择视频源json文件后软件无反应
> 
> 老哥 你怎么解决的

把93版本的文件删除用91版本的导入进去.再把91版本的文件删除.使用93版本
我这么说你能看得懂么?

**Comment by xiuzigege** [comment]
> > > 选择视频源json文件后软件无反应
> > 
> > 
> > 老哥 你怎么解决的
> 
> 把93版本的文件删除用91版本的导入进去.再把91版本的文件删除.使用93版本
> 我这么说你能看得懂么?

谢谢啦

**Comment by rog-mail** [comment]
> > > > 选择视频源json文件后软件无反应
> > > 
> > > 
> > > 老哥 你怎么解决的
> > 
> > 
> > 把93版本的文件删除用91版本的导入进去.再把91版本的文件删除.使用93版本
> > 我这么说你能看得懂么?
> 
> 谢谢啦

为更好的作品做贡献应该的,
