### ISSUE TITLE
win7 32bit无法使用？

### ISSUE THREAD

**Issue by gogo008** [ZyqGitHub1/h-player-v2#59]
不支持win7 32位系统吗，提示不支持

**Comment by ZyqGitHub1** [comment]
Currently only 64-bit system versions are available

------

目前仅提供64位系统版本

**Comment by ZyqGitHub1** [comment]
0.9.4版本的百度云盘下载渠道中添加了32位版本，文件名为h-player-0.9.4-ia32-win.zip，请下载测试
